- name: Docker host configuration
  hosts: localhost
  remote_user: root
  become: yes
  vars:
    path: /home/khirou/Desktop/pfe/dashboard/dashboard/board/utils/checks
  tasks:
    - name: executing CIS number 6
      shell: "{{ path }}/check6.{{ item }}.sh >> /tmp/log6"
      loop:
        - 1
        - 2
