- name: Docker host configuration
  remote_user: root
  become: yes
  hosts: all
  vars:
    path: /home/khirou/Desktop/pfe/dashboard/dashboard/board/utils/checks
  tasks:
    - name: executing CIS number 6
      shell: "{{ path }}/check6.{{ item }}.sh >> /tmp/log6-{{ inventory_hostname }}"
      loop:
        - 1
        - 2
