- name: Docker host configuration
  remote_user: root
  become: yes
  hosts: all
  vars:
    path: /home/khirou/Desktop/pfe/dashboard/dashboard/board/utils/checks
  tasks:
    - name: executing CIS number 7
      shell: "{{ path }}/check7.{{ item }}.sh >> /tmp/log7-{{ inventory_hostname }}"
      loop:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
